Repository trade-tariff/trade-tariff-testing, pull requests merged in 2021-09, with the labels that each got.

#370 Retain reports
  .github/workflows/regression.yml
  .github/workflows/regressionStaging.yml
Labels: GHA

#375 cypress@8.4.1
  package.json
  yarn.lock
Labels: Cypress Upgrade

#387 Cypress Update cypress@8.5.0
  package.json
  yarn.lock
Labels: Cypress Update
