Repository trade-tariff/trade-tariff-testing, pull requests merged in 2022-08, with the labels that each got.

#833 HOTT-1804 Searching for a quota with EU country does not show quota details
  cypress/e2e/Quotas/quotasSearch-UK.spec.js
Labels: bug fix

#836 RoO e2e journeys - WO+multipleschemes+GSP , WO+multipleschemes+nonGSP
  cypress/e2e/RulesOfOrigin/RoO-e2e-WhollyObtained/RoO-e2e-WO-Multiple-GSP.spec.js
  cypress/e2e/RulesOfOrigin/RoO-e2e-WhollyObtained/RoO-e2e-WO-Multiple-nonGSP.spec.js
  cypress/support/rooCommands.js
Labels: RoO, Sprint

#837 Regression fixes
  cypress/e2e/HOTT-Shared/docCodePopUps.spec.js
  cypress/e2e/Quotas/quotasSearch-UK.spec.js
  cypress/e2e/RulesOfOrigin/componentsDefRoO.spec.js
  cypress/e2e/RulesOfOrigin/importExportPageRoO.spec.js
  cypress/e2e/RulesOfOrigin/importOnlyPageRoO.spec.js
Labels: Refactor Regression

#838 Regression fixes
  cypress/e2e/DutyCalculator/3.RoW-NI/RoW-NI309--e2e.spec.js
  cypress/e2e/HOTT-Shared/subheadings.spec.js
  cypress/e2e/RulesOfOrigin/selectAgreementRoO.spec.js
  cypress/e2e/UK/UKMobile/smokeTest-UK-M.spec.js
  cypress/e2e/XI/FE/quotas-PR-XI.spec.js
Labels: Refactor Regression

#839 RoO-e2e-NWO-OneScheme-InsuffProcess + RoO rooCommands
  cypress/e2e/RulesOfOrigin/RoO-e2e-NotWhollyObtained/RoO-e2e-NWO-OneScheme-InsuffProcess.spec.js
  cypress/support/rooCommands.js
Labels: RoO, Sprint

#840 RoO-e2e-NWO-OneScheme-SuffProcess + PSR Yes/No
  cypress/e2e/RulesOfOrigin/RoO-e2e-NotWhollyObtained/RoO-e2e-NWO-OneScheme-SuffProcess.spec.js
Labels: RoO, Sprint

#846 Fix dev smoke tests based on Beta Search UI changes
  cypress/e2e/HOTT-Shared/devSmokeTestCI.spec.js
Labels: Refactor Regression

#849 HOTT-1794 Critical notes warning message on comm code pages
  cypress/e2e/HOTT-Shared/conditionsFootnotes.spec.js
Labels: Sprint

#850 RoO e2e - NWO + Multi-NonGSP + Sufficient processing + SubDivision + PSR
  cypress/e2e/RulesOfOrigin/RoO-e2e-NotWhollyObtained/RoO-e2e-NWO-MultiScheme-NonGSP-SuffProc.spec.js
  cypress/support/rooCommands.js
Labels: RoO, Sprint

#851 Regression fixes
  cypress/e2e/DutyCalculator/3.RoW-NI/RoW-NI309--e2e.spec.js
  cypress/e2e/HOTT-Shared/docCodePopUps.spec.js
  cypress/e2e/UK/FE/pages-UK.spec.js
  cypress/e2e/XI/FE/conditionCodes-XI.spec.js
Labels: Refactor Regression

#854 RoO-e2e-NWO-OneSchm-SuffPro-subdiv
  cypress/e2e/RulesOfOrigin/RoO-e2e-NotWhollyObtained/RoO-e2e-NWO-OneSchm-SuffPro-subdiv.spec.js
Labels: RoO, Sprint

#855 Refactor RoO e2e journeys
  cypress/e2e/RulesOfOrigin/RoO-e2e-NotWhollyObtained/RoO-e2e-NWO-GSP-InsuffPro.spec.js
  cypress/e2e/RulesOfOrigin/RoO-e2e-NotWhollyObtained/RoO-e2e-NWO-MultiSchm-NonGSP-SuffPro.spec.js
  cypress/e2e/RulesOfOrigin/RoO-e2e-NotWhollyObtained/RoO-e2e-NWO-OneSchm-InsuffPro.spec.js
  cypress/e2e/RulesOfOrigin/RoO-e2e-NotWhollyObtained/RoO-e2e-NWO-OneSchm-SuffPro.spec.js
  cypress/e2e/RulesOfOrigin/RoO-e2e-WhollyObtained/RoO-e2e-WO-GSP.spec.js
  cypress/e2e/RulesOfOrigin/RoO-e2e-WhollyObtained/RoO-e2e-WO-Multi-GSP.spec.js
  cypress/e2e/RulesOfOrigin/RoO-e2e-WhollyObtained/RoO-e2e-WO-Multi-nonGSP.spec.js
  cypress/e2e/RulesOfOrigin/RoO-e2e-WhollyObtained/RoO-e2e-WO-Multiple-nonGSP.spec.js
  cypress/e2e/RulesOfOrigin/RoO-e2e-WhollyObtained/RoO-e2e-WO-OneSchm.spec.js
  cypress/support/rooCommands.js
Labels: RoO, Sprint

#856 RoO-e2e-NWO-MultiSchm-NonGSP-InsuffPro
  cypress/e2e/RulesOfOrigin/RoO-e2e-NotWhollyObtained/RoO-e2e-NWO-MultiSchm-NonGSP-InsuffPro.spec.js
Labels: RoO, Sprint

#857 Regression fix
  cypress/e2e/HOTT-Shared/geoAreasPage.spec.js
Labels: Refactor Regression

#858 Fix devSmokeTestCI - Main page changes - UK and XI
  cypress/e2e/HOTT-Shared/devSmokeTestCI.spec.js
  cypress/support/commands.js
Labels: Refactor Regression

#862 HOTT-1919 Remove Quotas interim message
  cypress/e2e/Quotas/quotasErrorMessage.spec.js
Labels: Sprint

#864 HOTT-1899 RoO tab modifications when no country is selected
  cypress/e2e/RulesOfOrigin/commodityPageRoO.spec.js
  cypress/support/rooCommands.js
Labels: RoO, Sprint

#865 HOTT-1871 Cumulation maps
  cypress/e2e/RulesOfOrigin/RoO-e2e-NotWhollyObtained/RoO-e2e-NWO-GSP-InsuffPro.spec.js
  cypress/e2e/RulesOfOrigin/RoO-e2e-NotWhollyObtained/RoO-e2e-NWO-MultiSchm-NonGSP-InsuffPro.spec.js
  cypress/e2e/RulesOfOrigin/RoO-e2e-NotWhollyObtained/RoO-e2e-NWO-MultiSchm-NonGSP-SuffPro.spec.js
  cypress/e2e/RulesOfOrigin/RoO-e2e-NotWhollyObtained/RoO-e2e-NWO-OneSchm-InsuffPro.spec.js
  cypress/e2e/RulesOfOrigin/RoO-e2e-NotWhollyObtained/RoO-e2e-NWO-OneSchm-SuffPro-subdiv.spec.js
  cypress/e2e/RulesOfOrigin/RoO-e2e-NotWhollyObtained/RoO-e2e-NWO-OneSchm-SuffPro.spec.js
  cypress/support/rooCommands.js
Labels: RoO, Sprint

#866 Regression fixes
  cypress/e2e/HOTT-Shared/testExample.spec.js
  cypress/e2e/STW/linksSTW-OTT.spec.js
  cypress/e2e/UK/FE/feedback-UK.spec.js
  cypress/e2e/UK/FE/pages-UK.spec.js
  cypress/e2e/XI/FE/feedback-XI.spec.js
  cypress/e2e/XI/FE/pages-XI.spec.js
  cypress/e2e/XI/FE/quotas-PR-XI.spec.js
  cypress/support/commands.js
Labels: Refactor Regression

#870 HOTT 1909 - Duty calculator fix saccharine issues
  cypress/e2e/DutyCalculator/2.RoW-GB/RoW-GB208--e2e.spec.js
  cypress/e2e/DutyCalculator/3.RoW-NI/RoW-NI309--e2e.spec.js
Labels: Sprint
