Repository trade-tariff/trade-tariff-testing, pull requests merged in 2022-09, with the labels that each got.

#872 Regression fixes - country selection mapping changes + RoO
  cypress/e2e/DutyCalculator/Meursing/meursingCalculations.spec.js
  cypress/e2e/HOTT-Shared/datePersistedURL.spec.js
  cypress/e2e/HOTT-Shared/excludedCountryList.spec.js
  cypress/e2e/HOTT-Shared/smokeTestTradeTariff.spec.js
  cypress/e2e/RulesOfOrigin/commodityPageRoO.spec.js
  cypress/e2e/RulesOfOrigin/componentsDefRoO.spec.js
  cypress/e2e/RulesOfOrigin/howtoreadRoO.spec.js
  cypress/e2e/RulesOfOrigin/importExportPageRoO.spec.js
  cypress/e2e/RulesOfOrigin/proofOfOrigin.spec.js
  cypress/e2e/RulesOfOrigin/relatedContentRoO.spec.js
  cypress/e2e/RulesOfOrigin/selectAgreementRoO.spec.js
  cypress/e2e/RulesOfOrigin/specialDesciptionRoO.spec.js
  cypress/e2e/RulesOfOrigin/tradingRelationshipsRoO.spec.js
  cypress/e2e/STW/importGuidanceLinkSTW.spec.js
  cypress/e2e/UK/FE/countrySelection-UK.spec.js
  cypress/e2e/UK/FE/e2eMozzarellaChile-UK.spec.js
  cypress/e2e/UK/UKMobile/smokeTest-UK-M.spec.js
  cypress/e2e/WhiteChocolateIceland-XI/whiteChocolateIceland-XI.js
  cypress/e2e/XI/API/excludedCountriesApi-XI.spec.js
  cypress/e2e/XI/FE/countrySelection-XI.spec.js
  cypress/e2e/XI/FE/e2eMozzarellaChile-XI.spec.js
  cypress/support/rooCommands.js
Labels: Refactor Regression

#873 Regression fixes
  cypress/e2e/HOTT-Shared/docCodePopUps.spec.js
  cypress/e2e/HOTT-Shared/excludedCountryList.spec.js
  cypress/e2e/HOTT-Shared/helpSection.spec.js
  cypress/e2e/HOTT-Shared/newsTab.spec.js
  cypress/e2e/HOTT-Shared/subheadings.spec.js
  cypress/e2e/HOTT-Shared/suppUnits.spec.js
  cypress/e2e/HOTT-Shared/testExample.spec.js
  cypress/e2e/HOTT-Shared/tradingPartnerCountryList.spec.js
  cypress/e2e/RulesOfOrigin/commodityPageRoO.spec.js
Labels: Refactor Regression

#880 HOTT-1902 Import Trade Summary box
  cypress/e2e/RulesOfOrigin/impTradeSumBoxRoOTab.spec.js
  cypress/support/rooCommands.js
Labels: Sprint

#884 Fix API Doc link test - links open in new tab
  cypress/e2e/UK/FE/pageLinks-UK.spec.js
  cypress/e2e/XI/FE/pageLinks-XI.spec.js
  cypress/support/commands.js
Labels: Enhancement, Refactor Regression

#886 HOTT 1932/1975 - Import control section - prohibitions
  cypress/e2e/HOTT-Shared/impControlsSection.spec.js
Labels: Sprint

#887 HOTT-1427 Searching for Quotas using EU country
  cypress/e2e/Quotas/quotasSearch-UK.spec.js
Labels: Bug Fix, Sprint

#888 Regression fixes
  cypress/e2e/RulesOfOrigin/impTradeSumBoxRoOTab.spec.js
  cypress/e2e/UK/FE/countrySelection-UK.spec.js
  cypress/e2e/XI/FE/countrySelection-XI.spec.js
  yarn.lock
Labels: Refactor Regression

#889 Regression fixe - yarn issue
  yarn.lock
Labels: Plugins and Dependencies, Refactor Regression

#890 HOTT-1996 Doc code pop up 999L code wording changes
  cypress/e2e/HOTT-Shared/docCodePopUps.spec.js
  cypress/support/commands.js
Labels: Sprint

#891 HOTT-1904 Adding new UI tests for RoO - Additional duties box conditional rules
  cypress/e2e/RulesOfOrigin/additionalDutiesBoxConditionalRulesRoO.spec.js
Labels: Sprint

#894 Add RoO export journeys + extend NWO e2e tests + Rename e2e journeys
  cypress/e2e/RulesOfOrigin/RoO-e2e-NotWhollyObtained/601-RoO-e2e-NWO-GSP-InsuffPro.spec.js
  cypress/e2e/RulesOfOrigin/RoO-e2e-NotWhollyObtained/602-RoO-e2e-NWO-MultiSchm-NonGSP-InsuffPro.spec.js
  cypress/e2e/RulesOfOrigin/RoO-e2e-NotWhollyObtained/603-RoO-e2e-NWO-MultiSchm-NonGSP-SuffPro.spec.js
  cypress/e2e/RulesOfOrigin/RoO-e2e-NotWhollyObtained/604-RoO-e2e-NWO-OneSchm-InsuffPro.spec.js
  cypress/e2e/RulesOfOrigin/RoO-e2e-NotWhollyObtained/605-RoO-e2e-NWO-OneSchm-SuffPro-subdiv.spec.js
  cypress/e2e/RulesOfOrigin/RoO-e2e-NotWhollyObtained/606-RoO-e2e-NWO-OneSchm-SuffPro.spec.js
  cypress/e2e/RulesOfOrigin/RoO-e2e-NotWhollyObtained/RoO-e2e-NWO-MultiSchm-NonGSP-InsuffPro.spec.js
  cypress/e2e/RulesOfOrigin/RoO-e2e-NotWhollyObtained/RoO-e2e-NWO-OneSchm-InsuffPro.spec.js
  cypress/e2e/RulesOfOrigin/RoO-e2e-NotWhollyObtained/RoO-e2e-NWO-OneSchm-SuffPro-subdiv.spec.js
  cypress/e2e/RulesOfOrigin/RoO-e2e-NotWhollyObtained/RoO-e2e-NWO-OneSchm-SuffPro.spec.js
  cypress/e2e/RulesOfOrigin/RoO-e2e-WhollyObtained/701-RoO-e2e-WO-GSP.spec.js
  cypress/e2e/RulesOfOrigin/RoO-e2e-WhollyObtained/702-RoO-e2e-WO-Multi-GSP.spec.js
  cypress/e2e/RulesOfOrigin/RoO-e2e-WhollyObtained/703-RoO-e2e-WO-Multi-nonGSP.spec.js
  cypress/e2e/RulesOfOrigin/RoO-e2e-WhollyObtained/704-RoO-e2e-WO-OneSchm.spec.js
  cypress/e2e/RulesOfOrigin/commodityPageRoO.spec.js
  cypress/support/rooCommands.js
Labels: RoO, Sprint
